FROM python:3.10-slim

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

ENV PASSLIB_CRYPT_BACKEND=bcrypt
ENV PASSLIB_BCRYPT_DISABLE_WRAP_BUG_TEST=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY mitm.py .

CMD ["mitmdump", "-q", "-s", "mitm.py", "-p", "8080", "--set", "keep_host_header=true", "--set", "block_global=false"]

EXPOSE 8080

# mitmdump -s mitm.py -p 8080 --set keep_host_header=true
